apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.backend.container_port }}
  selector:
    app: {{ .Values.backend.name }}